# Generated by Django 3.2.7 on 2021-09-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(null=True)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=12, null=True)),
                ('lng', models.DecimalField(decimal_places=9, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=63)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='compro.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComproMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='compro/photos')),
                ('video', models.FileField(upload_to='compro/videos')),
                ('compro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='media', to='compro.compro')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='compro',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='compro_items', to='compro.team'),
        ),
    ]
