# Generated by Django 3.2.7 on 2021-09-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indulgence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(default=1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indulgences', to='compro.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
