# Generated by Django 3.2.7 on 2021-09-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0002_indulgence'),
    ]

    operations = [
        migrations.AddField(
            model_name='indulgence',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
