# Generated by Django 3.2.7 on 2021-09-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0003_indulgence_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HollyCompro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=12, null=True)),
                ('lng', models.DecimalField(decimal_places=9, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='compro',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='compro',
            name='lng',
        ),
        migrations.CreateModel(
            name='HollyComproAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='acquisitions', to='compro.hollycompro')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compro_acquisitions', to='compro.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
