# Generated by Django 3.2.7 on 2021-09-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0004_auto_20210905_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='hollycompro',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
