# Generated by Django 3.2.7 on 2021-09-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compro', '0007_auto_20210906_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentationmedia',
            name='image',
        ),
        migrations.RemoveField(
            model_name='documentationmedia',
            name='video',
        ),
        migrations.AddField(
            model_name='documentationmedia',
            name='multimedia',
            field=models.FileField(default=None, help_text='Fotka nebo video', upload_to='documentation'),
            preserve_default=False,
        ),
    ]
